
import { Calendar, Code, FileText, User, Clock, Hash, Bot, Briefcase } from "lucide-react";
import { PlaceHolderImages } from '@/lib/placeholder-images';

export const products = [
    {
      id: 1,
      title: 'TMS - Team Management System',
      shortTitle: '"Manage better . Perform Smarter"',
      slug: 'tms-team-management-system',
      description: 'T.M.S brings structure, clarity, and transparency to team operations by centralizing tasks, projects, meetings, and performance insights into one unified system. Every role — from employees to managers and clients — gets a clear, role-specific view of their responsibilities. T.M.S eliminates manual follow-ups, improves collaboration, and gives organizations a smarter way to manage work at scale.',
      link: 'https://images.unsplash.com/photo-1543269865-cbf427effbad?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw5fHx0ZWFtJTIwY29sbGFib3JhdGlvbnxlbnwwfHx8fDE3NTk3NzQzNDd8MA&ixlib-rb-4.1.0&q=80&w=1080',
      color: '#5196fd',
      releaseDate: 'Jan 2024',
      category: 'Productivity',
      icon: Briefcase,
      fullDescription: 'TMS is an all-in-one solution for modern teams. It combines task management, real-time communication, and performance tracking to help your team stay aligned and productive. Say goodbye to scattered tools and hello to streamlined success.',
      features: [
        'Agile and Kanban boards',
        'Real-time chat and collaboration',
        'Time tracking and reporting',
        'Gantt charts and project timelines',
      ],
      problemStatement: "Teams often struggle with disjointed tools for communication, task tracking, and project planning, leading to inefficiencies, missed deadlines, and a lack of visibility into project progress.",
      solutionsOffered: [
          "A unified platform for all project-related activities.",
          "Clear visibility into team workload and project status.",
          "Automated workflows to reduce manual overhead.",
          "Integrations with popular tools like Git, Slack, and Figma.",
      ],
      toolsTechStack: [
          { name: 'React', icon: 'Code' },
          { name: 'Node.js', icon: 'Server' },
          { name: 'PostgreSQL', icon: 'Server' },
          { name: 'GraphQL', icon: 'Code' },
          { name: 'WebSocket', icon: 'Bot' },
      ],
      caseStudies: [
          { title: "Startup increases velocity by 30%", description: "How a fast-growing startup used TMS to streamline their development process and ship features faster.", link: "#" },
      ],
    },
    {
      id: 2,
      title: 'RMS - Resource Management System',
      shortTitle: '“Smarter Workflows. Happier Employees.”',
      slug: 'rms-resource-management-system',
      description: 'R.M.S helps organizations manage people, tools, and operational resources with precision and clarity. It centralizes all resource data, provides role-based visibility, and enables intelligent allocation across teams and projects. With R.M.S, businesses can reduce inefficiencies, prevent overload, and ensure every resource is used effectively for maximum productivity.',
      link: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwzfHxyZXNvdXJjZSUyMG1hbmFnZW1lbnR8ZW58MHx8fHwxNzY1NTc3MTEyfDA&ixlib-rb-4.1.0&q=80&w=1080',
      color: '#8f89ff',
      releaseDate: 'Feb 2024',
      category: 'Operations',
      icon: User,
      fullDescription: 'RMS provides a bird\'s-eye view of your organization\'s resources, from personnel to equipment. Plan projects effectively, avoid bottlenecks, and ensure your resources are allocated for maximum impact.',
      features: [
        'Resource scheduling and allocation',
        'Skills and availability tracking',
        'Utilization and forecasting reports',
        'Project budget and cost management',
      ],
      problemStatement: "Organizations lack a clear, centralized view of their resources, leading to over-allocation, under-utilization, and difficulty in planning for future projects.",
      solutionsOffered: [
          "A real-time dashboard of all company resources.",
          "Forecasting tools to predict future resource needs.",
          "Skills-based resource matching for projects.",
          "Integration with HR and project management systems.",
      ],
      toolsTechStack: [
          { name: 'Vue.js', icon: 'Code' },
          { name: 'Django', icon: 'Server' },
          { name: 'MySQL', icon: 'Server' },
          { name: 'D3.js', icon: 'BarChart' },
      ],
      caseStudies: [
          { title: "Consulting firm improves billable hours by 20%", description: "By optimizing consultant allocation with RMS, the firm was able to increase their overall billable hours and profitability.", link: "#" },
      ],
    },
    {
      id: 3,
      title: 'WFx -  Wolfronix',
      shortTitle: '“Encrypt Once . Trust Forever.”',
      slug: 'wfx-wolfronix',
      description: 'W.F.X is a robust multi-layer security platform designed to safeguard digital systems with strong access controls, integrity monitoring, and privacy protection. It acts as a foundational shield for modern organizations, ensuring sensitive data remains secure and compliant while adapting seamlessly as infrastructures grow and evolve.',
      link: 'https://images.unsplash.com/photo-1611095790444-1dfa3c8a1f2w?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw0fHx3b3JrZmxvdyUyMGF1dG9tYXRpb258ZW58MHx8fHwxNzY1NTc3MTM4fDA&ixlib-rb-4.1.0&q=80&w=1080',
      color: '#13006c',
      releaseDate: 'Mar 2024',
      category: 'Security',
      icon: Bot,
      fullDescription: 'W.F.X by Wolfronix is a multi-layer security foundation that protects your data, access, and operations. It is designed for organizations that treat security as a core requirement, not an afterthought.',
      features: [
        'Multi-layer security enforcement',
        'Access & identity control hooks',
        'Data privacy protection mechanisms',
        'Integrity monitoring and alerting',
      ],
      problemStatement: "As digital footprints expand, organizations face increasing threats to their data, access points, and operational integrity. Traditional security measures are often siloed and fail to provide comprehensive protection against sophisticated, multi-pronged attacks.",
      solutionsOffered: [
          "Centralized security policy management.",
          "Fine-grained access control for users and services.",
          "Real-time monitoring and alerting for security events.",
          "A unified security model for hybrid and multi-cloud environments.",
      ],
      toolsTechStack: [
          { name: 'Go', icon: 'Code' },
          { name: 'Rust', icon: 'Code' },
          { name: 'Kubernetes', icon: 'Server' },
          { name: 'Prometheus', icon: 'BarChart' },
      ],
      caseStudies: [
          { title: "Fintech company secures customer data", description: "How W.F.X helped a fintech company implement a zero-trust security model, preventing unauthorized access and ensuring data privacy.", link: "#" },
      ],
    },
    {
      id: 4,
      title: 'CST - Customer Support Tool',
      shortTitle: '“Support Simplified. Results Magnified.”',
      slug: 'cst-customer-support-tool',
      description: 'C.S.T streamlines customer support by organizing service requests into clear, trackable tickets that guide both agents and customers through the entire resolution journey. With structured communication, real-time updates, and easy follow-up flows, C.S.T ensures faster responses, transparent progress, and a smoother support experience for teams and clients alike.',
      link: 'https://images.unsplash.com/photo-1611095782313-0b0a8f3c7f4e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxjdXN0b21lciUyMHN1cHBvcnR8ZW58MHx8fHwxNzY1NTc3MTY1fDA&ixlib-rb-4.1.0&q=80&w=1080',
      color: '#ed649e',
      releaseDate: 'Apr 2024',
      category: 'Customer Service',
      icon: FileText,
      fullDescription: 'CST is a modern help desk solution that brings all your customer conversations into one place. With powerful automations and an integrated knowledge base, your team can resolve issues faster and deliver exceptional service.',
      features: [
        'Omnichannel ticket management (email, chat, social)',
        'AI-powered ticket routing and categorization',
        'Integrated knowledge base',
        'Customer satisfaction (CSAT) surveys',
      ],
      problemStatement: "Customer support teams are overwhelmed with inquiries from multiple channels, leading to slow response times, inconsistent answers, and a poor customer experience.",
      solutionsOffered: [
          "A unified inbox for all customer interactions.",
          "AI-powered suggestions to help agents respond faster.",
          "A self-service portal and knowledge base to deflect common questions.",
          "Analytics to track team performance and customer satisfaction.",
      ],
      toolsTechStack: [
          { name: 'Svelte', icon: 'Code' },
          { name: 'Elixir', icon: 'Server' },
          { name: 'Phoenix', icon: 'Server' },
          { name: 'PostgreSQL', icon: 'Server' },
      ],
      caseStudies: [
          { title: "Online retailer reduces response time by 50%", description: "By implementing CST and its AI features, a retailer was able to handle a higher volume of tickets with the same team size.", link: "#" },
      ],
    },
    {
      id: 5,
      title: 'Hashtagger',
      shortTitle: '“Endless Limits. Endless privacy.”',
      slug: 'hashtagger',
      description: 'Hashtagger is a next-generation social platform built around hashtags, empowering users to explore their interests, connect through meaningful circles, and share content without sacrificing privacy. With AI-assisted features, multi-format content options, and a clean, distraction-free interface, Hashtagger offers a modern social experience that is both powerful and deeply secure.',
      link: 'https://images.unsplash.com/photo-1599507593498-27c936798797?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw0fHxoYXNodGFnfGVufDB8fHx8MTc2NTU3NzQ1N3ww&ixlib-rb-4.1.0&q=80&w=1080',
      color: '#00c7b2',
      releaseDate: 'May 2024',
      category: 'Social Media',
      icon: Hash,
      fullDescription: 'Hashtagger uses AI to analyze trending topics, competitor performance, and audience behavior to recommend the most effective hashtags for your social media posts. Track performance and optimize your strategy for maximum visibility.',
      features: [
        'AI-powered hashtag generation',
        'Performance analytics and tracking',
        'Competitor analysis',
        'Hashtag set management',
      ],
      problemStatement: "Brands struggle to keep up with ever-changing trends and algorithms on social media, making it difficult to choose effective hashtags that drive engagement and reach their target audience.",
      solutionsOffered: [
          "Automated hashtag suggestions tailored to your content.",
          "Real-time analytics on hashtag performance.",
          "Identification of niche and trending hashtags.",
          "Organization of hashtags into reusable sets.",
      ],
      toolsTechStack: [
          { name: 'Next.js', icon: 'Code' },
          { name: 'Python', icon: 'Code' },
          { name: 'FastAPI', icon: 'Server' },
          { name: 'MongoDB', icon: 'Server' },
      ],
      caseStudies: [
          { title: "Influencer grows engagement by 150%", description: "A lifestyle influencer used Hashtagger to optimize their Instagram posts, resulting in a 150% increase in engagement and a 50% growth in followers in 3 months.", link: "#" },
      ],
    }
  ];
